using LIMS.Shared.Core.Entities;

namespace LIMS.Shared.Core.Interfaces;

/// <summary>
/// Generic repository interface for data access.
/// Implementations are generated by LIMS.DAL.Generator from database schema.
/// </summary>
public interface IRepository<T> where T : BaseEntity
{
    Task<T?> GetByIdAsync(Guid id, CancellationToken cancellationToken = default);
    Task<IEnumerable<T>> GetAllAsync(CancellationToken cancellationToken = default);
    Task<IEnumerable<T>> FindAsync(string whereClause, object? parameters = null, CancellationToken cancellationToken = default);
    Task<T> AddAsync(T entity, CancellationToken cancellationToken = default);
    Task<bool> UpdateAsync(T entity, CancellationToken cancellationToken = default);
    Task<bool> DeleteAsync(Guid id, string deletedBy, CancellationToken cancellationToken = default);
    Task<int> CountAsync(string? whereClause = null, object? parameters = null, CancellationToken cancellationToken = default);
    Task<bool> ExistsAsync(Guid id, CancellationToken cancellationToken = default);

    // Temporal table queries
    Task<T?> GetByIdAsOfAsync(Guid id, DateTime asOf, CancellationToken cancellationToken = default);
    Task<IEnumerable<T>> GetHistoryAsync(Guid id, CancellationToken cancellationToken = default);
}

/// <summary>
/// Service interface for business logic.
/// Each domain module implements services for its entities.
/// </summary>
public interface IService<T> where T : BaseEntity
{
    Task<Result<T>> GetByIdAsync(Guid id);
    Task<Result<IEnumerable<T>>> GetAllAsync();
    Task<Result<T>> CreateAsync(T entity);
    Task<Result<T>> UpdateAsync(T entity);
    Task<Result> DeleteAsync(Guid id, string deletedBy);
}
