namespace LIMS.Shared.Core.Entities;

/// <summary>
/// Base entity with audit fields and soft delete support.
/// All domain entities inherit from this base.
/// </summary>
public abstract class BaseEntity
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public string CreatedBy { get; set; } = string.Empty;
    public DateTime? ModifiedAt { get; set; }
    public string? ModifiedBy { get; set; }
    public bool IsDeleted { get; set; }
    public DateTime? DeletedAt { get; set; }
    public string? DeletedBy { get; set; }

    // Temporal table columns (auto-generated by SQL Server)
    public DateTime ValidFrom { get; set; }
    public DateTime ValidTo { get; set; }
}
